import {readFile,writeFile} from 'node:fs/promises';
const token=process.env.TELEGRAM_BOT_TOKEN;if(!token){console.error('Set TELEGRAM_BOT_TOKEN');process.exit(1)}
const dbPath=new URL('./data/db.json',import.meta.url);const db=JSON.parse(await readFile(dbPath,'utf8'));const now=new Date();
function serviceDue(c){const km=Math.max(0,c.serviceIntervalKm-(c.odometer-c.lastServiceOdometer));const date=c.nextServiceDate?Math.ceil((new Date(`${c.nextServiceDate}T23:59:59`)-now)/86400000):null;return km<=0||(date!==null&&date<=0)}
function itemDue(m){const car=db.cars[m.carId];if(!car)return false;const km=m.intervalKm?m.intervalKm-(car.odometer-m.lastDoneOdometer):null;const days=m.nextDate?Math.ceil((new Date(`${m.nextDate}T23:59:59`)-now)/86400000):null;return (km!==null&&km<=0)||(days!==null&&days<=0)}
function scheduled(r){if(!r?.enabled)return false;const d=now.getDay(),h=String(now.getHours()).padStart(2,'0'),m=String(now.getMinutes()).padStart(2,'0');if(`${h}:${m}`!==r.time)return false;if(r.mode==='weekly')return d===Number(r.weekday);if(r.mode==='biweekly'){const week=Math.floor(now.getTime()/604800000);return d===Number(r.weekday)&&week%2===0}if(r.mode==='monthly')return now.getDate()===Number(r.monthlyDay||1);return false}
async function send(chat_id,text){const r=await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id,text})});if(!r.ok)throw new Error(await r.text())}
function dayKey(){return now.toISOString().slice(0,10)+' '+now.toISOString().slice(11,16)}
for(const u of Object.values(db.users)){if(!scheduled(u.reminder))continue;const key=`${u.id}:${dayKey()}`;if(db.reminderLog?.[key])continue;const cars=Object.values(db.cars).filter(c=>c.userId===u.id);if(!cars.length)continue;const dueCars=cars.filter(serviceDue);const items=Object.values(db.maintenance||{}).filter(x=>x.userId===u.id&&itemDue(x));const fines=Object.values(db.fines||{}).filter(f=>f.userId===u.id&&f.status==='unpaid');const overdue=fines.filter(f=>f.dueDate&&new Date(`${f.dueDate}T23:59:59`)<=now);let parts=[];if(dueCars.length)parts.push(`🔴 Общее ТО: ${dueCars.map(c=>c.name).join(', ')}`);if(items.length)parts.push(`🔧 Требуют внимания: ${items.map(m=>m.name).join(', ')}`);if(overdue.length)parts.push(`⚠️ Просроченные штрафы: ${overdue.length}`);if(!parts.length)parts.push(`📏 Напоминание о пробеге:\n${cars.map(c=>`🚗 ${c.name}: ${c.odometer.toLocaleString('ru-RU')} км`).join('\n')}`);else parts.unshift(`🚗 АвтоПлан — проверка автомобиля`);try{await send(u.id,parts.join('\n\n'));db.reminderLog[key]=true}catch(e){console.error('send failed',u.id,e.message)}}
await writeFile(dbPath,JSON.stringify(db,null,2));
