import http from 'node:http';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, extname, resolve, relative, isAbsolute } from 'node:path';
import { fileURLToPath } from 'node:url';
import crypto from 'node:crypto';
import { VEHICLE_KNOWLEDGE, getVehicleRecommendations, listVehicleModels } from './vehicle-knowledge.js';
import { partsMeta, partSearchExamples, findVehicle, listCatalogs, listCategories, listUnits, listDetailByUnit, searchVehicleDetails, wizard, wizardFind, quickGroups, quickDetails, freeFindVehicle, freeVinVehicle, freeManufacturers, freeModels, freeModifications, freeCategories, freeUnits, freeUnitDetails, freeSearch, freeAnalogs } from './parts-catalog.js';

const ROOT=fileURLToPath(new URL('.',import.meta.url));
const PUBLIC=join(ROOT,'public'); const DATA_DIR=join(ROOT,'data'); const DATA_FILE=join(DATA_DIR,'db.json');
const PORT=Number(process.env.PORT||3000); const KNOWLEDGE_UPDATE_URL=process.env.KNOWLEDGE_UPDATE_URL||''; const BOT_TOKEN=process.env.TELEGRAM_BOT_TOKEN||''; const WEBHOOK_SECRET=process.env.TELEGRAM_WEBHOOK_SECRET||'';
const emptyDb={users:{},cars:{},services:{},maintenance:{},fines:{},drivers:{},stations:{},stationReviews:{},bookings:{},promos:{},reminderLog:{},pendingMileage:{},stationViews:{},communityMessages:{},mileageHistory:{}};
const FINES_API_URL=process.env.FINES_API_URL||''; const FINES_API_TOKEN=process.env.FINES_API_TOKEN||''; const YANDEX_MAPS_JS_API_KEY=process.env.YANDEX_MAPS_JS_API_KEY||'';
let COMMUNITY_CHATS={};try{COMMUNITY_CHATS=JSON.parse(process.env.COMMUNITY_CHATS_JSON||'{}')}catch{COMMUNITY_CHATS={}}
const MAINTENANCE_PRESETS=[
 {key:'oil',name:'Моторное масло',intervalKm:10000,group:'engine'},
 {key:'oil_filter',name:'Масляный фильтр',intervalKm:10000,group:'engine'},
 {key:'air_filter',name:'Воздушный фильтр',intervalKm:15000,group:'engine'},
 {key:'fuel_filter',name:'Топливный фильтр',intervalKm:30000,group:'engine'},
 {key:'spark_plugs',name:'Свечи зажигания',intervalKm:30000,group:'engine'},
 {key:'engine_coolant',name:'Охлаждающая жидкость',intervalKm:60000,group:'fluids'},
 {key:'brake_fluid',name:'Тормозная жидкость',intervalKm:null,group:'brakes'},
 {key:'power_steering_fluid',name:'Жидкость ГУР',intervalKm:null,group:'fluids'},
 {key:'ac_service',name:'Обслуживание кондиционера',intervalKm:null,group:'fluids'},
 {key:'atf',name:'Масло АКПП / вариатора',intervalKm:60000,group:'transmission'},
 {key:'atf_filter',name:'Фильтр АКПП / вариатора',intervalKm:60000,group:'transmission'},
 {key:'mtf',name:'Масло МКПП',intervalKm:60000,group:'transmission'},
 {key:'dct_oil',name:'Масло роботизированной КПП',intervalKm:60000,group:'transmission'},
 {key:'transfer_oil',name:'Масло раздаточной коробки',intervalKm:60000,group:'axles'},
 {key:'front_diff_oil',name:'Масло переднего редуктора',intervalKm:60000,group:'axles'},
 {key:'rear_diff_oil',name:'Масло заднего редуктора / моста',intervalKm:60000,group:'axles'},
 {key:'cabin_filter',name:'Салонный фильтр',intervalKm:15000,group:'filters'},
 {key:'pads_front',name:'Передние тормозные колодки',intervalKm:null,group:'brakes'},
 {key:'pads_rear',name:'Задние тормозные колодки',intervalKm:null,group:'brakes'},
 {key:'discs_front',name:'Передние тормозные диски',intervalKm:null,group:'brakes'},
 {key:'discs_rear',name:'Задние тормозные диски',intervalKm:null,group:'brakes'},
 {key:'brake_hoses',name:'Тормозные шланги',intervalKm:null,group:'brakes'},
 {key:'timing_belt',name:'Ремень ГРМ',intervalKm:60000,group:'engine'},
 {key:'timing_chain',name:'Цепь ГРМ — проверка',intervalKm:null,group:'engine'},
 {key:'accessory_belt',name:'Ремень навесного оборудования',intervalKm:60000,group:'engine'},
 {key:'battery',name:'Аккумулятор — проверка',intervalKm:null,group:'electrical'},
 {key:'alternator',name:'Генератор — проверка',intervalKm:null,group:'electrical'},
 {key:'starter',name:'Стартер — проверка',intervalKm:null,group:'electrical'},
 {key:'cooling_system',name:'Система охлаждения — проверка',intervalKm:null,group:'engine'},
 {key:'thermostat',name:'Термостат — проверка',intervalKm:null,group:'engine'},
 {key:'injectors',name:'Форсунки — проверка/чистка',intervalKm:null,group:'engine'},
 {key:'throttle',name:'Дроссельная заслонка — проверка/чистка',intervalKm:null,group:'engine'},
 {key:'pcv',name:'Вентиляция картера — проверка',intervalKm:null,group:'engine'},
 {key:'engine_mounts',name:'Опоры двигателя — проверка',intervalKm:null,group:'engine'},
 {key:'shock_front',name:'Передние амортизаторы',intervalKm:null,group:'suspension_front'},
 {key:'shock_rear',name:'Задние амортизаторы',intervalKm:null,group:'suspension_rear'},
 {key:'ball_joint',name:'Шаровые опоры',intervalKm:null,group:'suspension_front'},
 {key:'tie_rods',name:'Рулевые наконечники / тяги',intervalKm:null,group:'steering'},
 {key:'control_arm_front',name:'Передние рычаги подвески',intervalKm:null,group:'suspension_front'},
 {key:'bushings_front',name:'Передние сайлентблоки',intervalKm:null,group:'suspension_front'},
 {key:'bushings_rear',name:'Задние сайлентблоки',intervalKm:null,group:'suspension_rear'},
 {key:'wheel_bearings',name:'Ступичные подшипники',intervalKm:null,group:'suspension'},
 {key:'cv_joints',name:'ШРУСы и пыльники',intervalKm:null,group:'suspension'},
 {key:'steering_fluid',name:'Рулевое управление — проверка',intervalKm:null,group:'steering'},
 {key:'clutch',name:'Сцепление',intervalKm:null,group:'transmission'},
 {key:'driveshaft',name:'Кардан / крестовины',intervalKm:null,group:'axles'},
 {key:'tires',name:'Шины — состояние и износ',intervalKm:null,group:'wheels'},
 {key:'alignment',name:'Развал-схождение',intervalKm:null,group:'wheels'},
 {key:'headlights',name:'Свет / фары — проверка',intervalKm:null,group:'electrical'},
 {key:'wipers',name:'Щётки стеклоочистителя',intervalKm:null,group:'body_other'},
 {key:'exhaust',name:'Выхлопная система — проверка',intervalKm:null,group:'exhaust'},
 {key:'catalyst',name:'Катализатор / сажевый фильтр — проверка',intervalKm:null,group:'exhaust'},
 {key:'oxygen_sensor',name:'Кислородные датчики — проверка',intervalKm:null,group:'engine'},
 {key:'egr',name:'EGR / система рециркуляции — проверка',intervalKm:null,group:'engine'},
 {key:'abs_esp',name:'ABS / ESP — проверка',intervalKm:null,group:'safety'},
 {key:'airbags',name:'Подушки безопасности — диагностика',intervalKm:null,group:'safety'},
 {key:'ac_filter',name:'Фильтр системы кондиционирования — обслуживание',intervalKm:null,group:'fluids'},
 {key:'suspension_repair',name:'Ремонт ходовой части',intervalKm:null,group:'suspension'},
 {key:'control_arm',name:'Рычаги подвески — ремонт',intervalKm:null,group:'suspension'},
 {key:'bushings',name:'Сайлентблоки — ремонт',intervalKm:null,group:'suspension'},
 {key:'engine_repair',name:'Ремонт двигателя',intervalKm:null,group:'engine'},
 {key:'electrical_repair',name:'Ремонт электрики',intervalKm:null,group:'electrical'}
];
async function loadDb(){await mkdir(DATA_DIR,{recursive:true});if(!existsSync(DATA_FILE)){await writeFile(DATA_FILE,JSON.stringify(emptyDb,null,2));return structuredClone(emptyDb)}try{return {...emptyDb,...JSON.parse(await readFile(DATA_FILE,'utf8'))}}catch{return structuredClone(emptyDb)}}
let db=await loadDb(); let saveTimer;
function saveSoon(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>writeFile(DATA_FILE,JSON.stringify(db,null,2)),100)}
async function saveNow(){clearTimeout(saveTimer);await writeFile(DATA_FILE,JSON.stringify(db,null,2))}
function id(p){return p+'_'+Date.now().toString(36)+'_'+crypto.randomBytes(4).toString('hex')}
function json(res,status,obj){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(obj))}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>2e6){reject(new Error('body_too_large'));req.destroy()}});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}});req.on('error',reject)})}
function ensureUser(uid,profile={}){if(!db.users[uid])db.users[uid]={id:uid,firstName:profile.first_name||'',username:profile.username||'',reminder:{enabled:true,mode:'weekly',weekday:0,time:'19:00',monthlyDay:1},createdAt:new Date().toISOString()};return db.users[uid]}
function validateTelegramInitData(initData){
  if(!BOT_TOKEN||!initData)return null;
  const p=new URLSearchParams(initData); const hash=p.get('hash'); if(!hash||!/^[a-f0-9]{64}$/i.test(hash))return null; p.delete('hash');
  const dataCheck=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n');
  const secret=crypto.createHmac('sha256','WebAppData').update(BOT_TOKEN).digest();
  const expected=crypto.createHmac('sha256',secret).update(dataCheck).digest('hex');
  if(!crypto.timingSafeEqual(Buffer.from(hash,'hex'),Buffer.from(expected,'hex')))return null;
  const authDate=Number(p.get('auth_date')); if(!authDate||Math.abs(Date.now()/1000-authDate)>86400)return null;
  try{return JSON.parse(p.get('user')||'null')}catch{return null}
}
function getUid(req){const tg=validateTelegramInitData(req.headers['x-telegram-init-data']||'');if(tg?.id)return String(tg.id);if(process.env.NODE_ENV!=='production')return req.headers['x-demo-user']||'demo-user';return null}
function normalizeOil(x={}){if(typeof x==='string')return {brand:'',name:x,viscosity:x,volume:''};return {brand:String(x.brand||'').slice(0,80),name:String(x.name||'').slice(0,120),viscosity:String(x.viscosity||'').slice(0,30),volume:String(x.volume||'').slice(0,30)}}
function normalizeCar(x){const n=Number(x.odometer),interval=Number(x.serviceIntervalKm);const oil=normalizeOil(x.oil&&typeof x.oil==='object'?x.oil:{brand:x.oilBrand,name:x.oilName,viscosity:x.oilViscosity||x.oil,volume:x.oilVolume});const mr=x.mileageReminder||{};return {...x,id:x.id||id('car'),stsNumber:String(x.stsNumber||''),name:String(x.name||`${x.make||''} ${x.model||''}`).trim()||'Мой автомобиль',make:String(x.make||''),model:String(x.model||''),year:Number.isFinite(Number(x.year))?Number(x.year):null,color:String(x.color||''),plate:String(x.plate||''),vin:String(x.vin||''),odometer:Number.isFinite(n)&&n>=0?n:0,serviceIntervalKm:Number.isFinite(interval)&&interval>0?interval:10000,lastServiceOdometer:Number.isFinite(Number(x.lastServiceOdometer))?Number(x.lastServiceOdometer):Number.isFinite(n)&&n>=0?n:0,nextServiceDate:/^\d{4}-\d{2}-\d{2}$/.test(x.nextServiceDate||'')?x.nextServiceDate:null,lastServiceDate:/^\d{4}-\d{2}-\d{2}$/.test(x.lastServiceDate||'')?x.lastServiceDate:null,reminderKm:Number.isFinite(Number(x.reminderKm))?Math.max(0,Number(x.reminderKm)):1000,reminderDays:Number.isFinite(Number(x.reminderDays))?Math.max(0,Number(x.reminderDays)):0,oil,oilVolume:oil.volume,mileageReminder:{enabled:mr.enabled!==false,mode:['interval','monthly'].includes(mr.mode)?mr.mode:'interval',intervalDays:Math.min(30,Math.max(1,Number(mr.intervalDays)||7)),monthlyDay:Math.min(31,Math.max(1,Number(mr.monthlyDay)||1)),lastAskedAt:mr.lastAskedAt||null},createdAt:x.createdAt||new Date().toISOString()}}
function due(car,now=new Date()){const km=Math.max(0,car.serviceIntervalKm-(car.odometer-car.lastServiceOdometer));const date=car.nextServiceDate?Math.ceil((new Date(`${car.nextServiceDate}T23:59:59`)-now)/86400000):null;return{kmRemaining:km,dateRemaining:date,dueByKm:km<=0,dueByDate:date!==null&&date<=0,due:km<=0||(date!==null&&date<=0)}}
function safeCar(c){return {...c,due:due(c)}}
function normalizeStation(x){return {...x,userId:String(x.userId||''),id:x.id||id('station'),name:String(x.name||'СТО').slice(0,160)}}
function normalizeMaintenance(x){return {...x,userId:String(x.userId||''),carId:String(x.carId||''),id:x.id||id('maint')}}
function normalizeService(x){return {...x,userId:String(x.userId||''),carId:String(x.carId||''),id:x.id||id('svc')}}
function normalizeStationView(x){return {...x,userId:String(x.userId||''),id:x.id||id('view')}}
function normalizeMileageHistory(x){return {...x,userId:String(x.userId||''),carId:String(x.carId||''),odometer:Number(x.odometer||0),recordedAt:x.recordedAt||new Date().toISOString(),id:x.id||id('mile')}}
async function refreshKnowledge(){if(!KNOWLEDGE_UPDATE_URL)return {updated:false,reason:'not_configured'};try{const r=await fetch(KNOWLEDGE_UPDATE_URL,{headers:{accept:'application/json'},signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error(`http_${r.status}`);const data=await r.json();const rows=Array.isArray(data)?data:(Array.isArray(data.rules)?data.rules:[]);let added=0;for(const x of rows){if(!x||!x.make||!x.model||!Number.isFinite(Number(x.mileage)))continue;const rule={make:String(x.make),model:String(x.model),minYear:Number(x.minYear)||0,maxYear:Number(x.maxYear)||9999,mileage:Number(x.mileage),title:String(x.title||'Профилактическая проверка').slice(0,160),description:String(x.description||'Проверить узел по регламенту производителя.').slice(0,600),category:String(x.category||'general').slice(0,60),source:String(x.source||'remote knowledge feed').slice(0,200)};const exists=VEHICLE_KNOWLEDGE.some(z=>z.make===rule.make&&z.model===rule.model&&z.mileage===rule.mileage&&z.title===rule.title&&z.minYear===rule.minYear&&z.maxYear===rule.maxYear);if(!exists){VEHICLE_KNOWLEDGE.push(rule);added++}}return {updated:true,added,total:VEHICLE_KNOWLEDGE.length}}catch(e){console.error('knowledge refresh failed',e.message);return {updated:false,error:e.message}}}
function suspiciousMileage(car,value){const current=Number(car?.odometer||0),v=Number(value);if(!current||!Number.isFinite(v))return null;const delta=v-current;const pct=current?delta/current:0;const suspicious=delta>10000&&pct>0.12;return suspicious?{current,entered:v,delta,percent:Math.round(pct*100)}:null}
function recordMileage(uid,car,value,source='manual'){const v=Number(value);if(!Number.isFinite(v)||v<0)return null;const day=new Date().toISOString();const k=id('mile');const rec={id:k,userId:uid,carId:car.id,odometer:v,recordedAt:day,source};db.mileageHistory[k]=rec;return rec}
function validWebhook(req){return !WEBHOOK_SECRET||req.headers['x-telegram-bot-api-secret-token']===WEBHOOK_SECRET}
async function telegram(method,payload){if(!BOT_TOKEN)throw new Error('telegram_token_missing');const r=await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.description||`telegram_${method}_failed`);return d.result}
async function handleUpdate(u){const msg=u?.message;if(!msg?.chat?.id)return;const uid=String(msg.chat.id);const user=ensureUser(uid,msg.from||{});const text=String(msg.text||'').trim();
  if(text==='/start'||text==='/help'){await telegram('sendMessage',{chat_id:uid,text:'🚗 АвтоПлан\n\nОткройте приложение, чтобы добавить автомобиль, настроить ТО и напоминания.',reply_markup:{inline_keyboard:[[ {text:'🚗 Открыть АвтоПлан',web_app:{url:process.env.MINI_APP_URL||'https://example.com'}} ]]}});return}
  if(db.pendingMileage[uid]){const car=db.cars[db.pendingMileage[uid].carId];const value=Number(text.replace(/[^0-9.]/g,''));if(car&&car.userId===uid&&Number.isFinite(value)&&value>=car.odometer){car.odometer=value;recordMileage(uid,car,value,'telegram');delete db.pendingMileage[uid];saveSoon();await telegram('sendMessage',{chat_id:uid,text:`✅ Пробег сохранён: ${value.toLocaleString('ru-RU')} км`});return}}
  if(/^\d+[,.]?\d*$/.test(text)){await telegram('sendMessage',{chat_id:uid,text:'Если приложение попросило обновить пробег, отправьте число ещё раз. Для управления автомобилем откройте Mini App.'});return}
  ensureUser(uid,user); saveSoon();
}

function normalizeDriver(x){return {id:x.id||id('driver'),userId:String(x.userId||''),name:String(x.name||'').slice(0,160),licenseNumber:String(x.licenseNumber||'').replace(/\s+/g,'').slice(0,30),licenseIssueDate:/^\d{4}-\d{2}-\d{2}$/.test(x.licenseIssueDate||'')?x.licenseIssueDate:null,createdAt:x.createdAt||new Date().toISOString()}}
async function fetchFineProvider(payload){if(!FINES_API_URL)return {configured:false,fines:[]};const r=await fetch(FINES_API_URL,{method:'POST',headers:{'content-type':'application/json',...(FINES_API_TOKEN?{'authorization':`Bearer ${FINES_API_TOKEN}`}:{})},body:JSON.stringify(payload)});if(!r.ok)throw new Error('fines_provider_failed');const d=await r.json();return {configured:true,fines:Array.isArray(d.fines)?d.fines:[]}}
function normalizeFine(x){
 const amount=Math.max(0,Number(x.amount)||0);
 const date=/^\d{4}-\d{2}-\d{2}$/.test(x.date||'')?x.date:new Date().toISOString().slice(0,10);
 const dueDate=/^\d{4}-\d{2}-\d{2}$/.test(x.dueDate||'')?x.dueDate:null;
 return {id:x.id||id('fine'),userId:String(x.userId||''),carId:String(x.carId||''),date,dueDate,amount,article:String(x.article||'').slice(0,120),description:String(x.description||'').slice(0,500),status:['unpaid','paid','disputed'].includes(x.status)?x.status:'unpaid',externalId:String(x.externalId||'').slice(0,100),source:String(x.source||'provider').slice(0,40),createdAt:x.createdAt||new Date().toISOString()};
}
function fineDue(f){return f.status==='unpaid' && !!f.dueDate && new Date(`${f.dueDate}T23:59:59`)<=new Date()}
function stationDistance(lat1,lon1,lat2,lon2){const R=6371;const p=Math.PI/180;const a=0.5-Math.cos((lat2-lat1)*p)/2+Math.cos(lat1*p)*Math.cos(lat2*p)*(1-Math.cos((lon2-lon1)*p))/2;return R*2*Math.asin(Math.sqrt(a))}
async function searchStations(text,lat,lon){
 const key=process.env.YANDEX_SEARCH_API_KEY;
 if(!key)return {provider:'none',stations:[]};
 const qs=new URLSearchParams({apikey:key,text:text||'автосервис',type:'biz',lang:'ru_RU',results:'20'});
 if(Number.isFinite(lat)&&Number.isFinite(lon)){qs.set('ll',`${lon},${lat}`);qs.set('spn','0.25,0.25');qs.set('rspn','1')}
 const r=await fetch(`https://search-maps.yandex.ru/v1/?${qs}`); if(!r.ok)throw new Error('station_search_failed'); const d=await r.json();
 const features=Array.isArray(d.features)?d.features:[];
 return {provider:'yandex',stations:features.map(f=>{const c=f.geometry?.coordinates||[];const p=f.properties||{};const meta=p.CompanyMetaData||{};const name=meta.name||p.name||'СТО';const addr=meta.address||p.description||'';const phone=(meta.Phones||[])[0]?.formatted||'';const hours=(meta.Hours?.text)||'';const coords=Array.isArray(c)&&c.length===2?{lat:c[1],lon:c[0]}:null;const distance=coords&&Number.isFinite(lat)&&Number.isFinite(lon)?stationDistance(lat,lon,coords.lat,coords.lon):null;const local=Object.values(db.stations).find(x=>x.externalId===String(meta.id||'')); const ss=stationSummary(String(meta.id||'')); return {id:meta.id||id('ext'),name,address:addr,phone,hours,coords,distance,sponsored:!!local?.sponsored,source:'yandex',rating:ss.rating,reviews:ss.reviews};}).sort((a,b)=>(a.distance??9999)-(b.distance??9999))};
}
function ownedStation(s,uid){return s&&s.userId===uid}
function normalizeReview(x){const rating=Math.min(5,Math.max(1,Number(x.rating)||5));return {id:x.id||id('review'),stationId:String(x.stationId||''),userId:String(x.userId||''),rating,comment:String(x.comment||'').slice(0,1000),createdAt:x.createdAt||new Date().toISOString()}}
function stationSummary(stationId){const rs=Object.values(db.stationReviews||{}).filter(r=>r.stationId===stationId);const rating=rs.length?rs.reduce((a,r)=>a+r.rating,0)/rs.length:0;return {rating:Math.round(rating*10)/10,reviews:rs.length}}
function normalizeBooking(x){return {id:x.id||id('booking'),userId:String(x.userId||''),stationId:String(x.stationId||''),carId:String(x.carId||''),date:/^\d{4}-\d{2}-\d{2}$/.test(x.date||'')?x.date:'',time:/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(x.time||'')?x.time:'',service:String(x.service||'ТО').slice(0,160),comment:String(x.comment||'').slice(0,500),status:['requested','confirmed','cancelled','done'].includes(x.status)?x.status:'requested',createdAt:x.createdAt||new Date().toISOString()}}
function normalizePromo(x){return {id:x.id||id('promo'),stationId:String(x.stationId||''),code:String(x.code||'').trim().toUpperCase().slice(0,40),title:String(x.title||'Промокод').slice(0,160),description:String(x.description||'').slice(0,500),discount:String(x.discount||'').slice(0,80),active:x.active!==false,validUntil:/^\d{4}-\d{2}-\d{2}$/.test(x.validUntil||'')?x.validUntil:null,createdAt:x.createdAt||new Date().toISOString()}}
function communityKey(make,model){return `${String(make||'').trim().toUpperCase()} ${String(model||'').trim().toUpperCase()}`.trim()}
function normalizeCommunityMessage(x){return {id:x.id||id('cmsg'),userId:String(x.userId||''),make:String(x.make||''),model:String(x.model||''),text:String(x.text||'').trim().slice(0,2000),replyTo:x.replyTo?String(x.replyTo):null,authorName:String(x.authorName||'Владелец').slice(0,100),createdAt:x.createdAt||new Date().toISOString()}}
async function route(req,res){
 const url=new URL(req.url,`http://${req.headers.host}`);
 if(req.method==='GET'&&url.pathname==='/health')return json(res,200,{ok:true,version:'2.7.0',telegramAuth:!!BOT_TOKEN,webhookConfigured:!!WEBHOOK_SECRET});
 if(req.method==='POST'&&url.pathname==='/telegram/webhook'){if(!validWebhook(req))return json(res,403,{error:'invalid_webhook_secret'});try{await handleUpdate(await body(req));return json(res,200,{ok:true})}catch(e){console.error(e);return json(res,500,{error:'webhook_error'})}}
 const uid=getUid(req); if(url.pathname!=='/'&&url.pathname!=='/index.html'&&url.pathname!=='/favicon.ico'&&!uid)return json(res,401,{error:'telegram_auth_required'}); if(uid)ensureUser(uid);
 if(req.method==='GET'&&url.pathname==='/api/app-meta'){return json(res,200,{name:'АвтоПлан',version:'2.7.0',stage:'test-build',focus:'maintenance-first',productionReady:false,finesProviderConfigured:!!FINES_API_URL,yandexMapsConfigured:!!YANDEX_MAPS_JS_API_KEY,mapsApiKey:YANDEX_MAPS_JS_API_KEY,partsCatalogConfigured:partsMeta().configured,partsCatalogProvider:partsMeta().provider})}
 if(req.method==='GET'&&url.pathname==='/api/maintenance/presets'){return json(res,200,{presets:MAINTENANCE_PRESETS})}
 if(req.method==='GET'&&url.pathname==='/api/parts/free/vin'){try{const vin=String(url.searchParams.get('vin')||'').trim().toUpperCase();if(!vin)return json(res,400,{error:'vin_required'});return json(res,200,{vehicle:await freeVinVehicle(vin)})}catch(e){return json(res,503,{error:e.message||'free_vin_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/free/manufacturers'){try{return json(res,200,{manufacturers:await freeManufacturers()})}catch(e){return json(res,503,{error:e.message||'free_parts_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/free/models'){try{const mfi=url.searchParams.get('mfi');if(!mfi)return json(res,400,{error:'manufacturer_required'});return json(res,200,{models:await freeModels(mfi)})}catch(e){return json(res,503,{error:e.message||'free_parts_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/free/modifications'){try{const mdi=url.searchParams.get('mdi');if(!mdi)return json(res,400,{error:'model_required'});return json(res,200,{modifications:await freeModifications(mdi)})}catch(e){return json(res,503,{error:e.message||'free_parts_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/free/vehicle'){try{const car={make:url.searchParams.get('make')||'',model:url.searchParams.get('model')||'',year:url.searchParams.get('year')||'',engine:url.searchParams.get('engine')||'',transmission:url.searchParams.get('transmission')||''};if(!car.make||!car.model)return json(res,400,{error:'vehicle_required'});return json(res,200,{vehicle:await freeFindVehicle(car)})}catch(e){return json(res,503,{error:e.message||'free_parts_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/free/categories'){try{const v={catalog:'free',vehicleId:url.searchParams.get('vehicleId')};if(!v.vehicleId)return json(res,400,{error:'vehicle_context_required'});return json(res,200,{categories:await freeCategories(v)})}catch(e){return json(res,503,{error:e.message||'free_parts_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/free/units'){try{const v={catalog:'free',vehicleId:url.searchParams.get('vehicleId')};if(!v.vehicleId)return json(res,400,{error:'vehicle_context_required'});return json(res,200,{units:await freeUnits(v,url.searchParams.get('categoryId')||'-1')})}catch(e){return json(res,503,{error:e.message||'free_parts_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/free/unit-details'){try{const v={catalog:'free',vehicleId:url.searchParams.get('vehicleId')},unitId=url.searchParams.get('unitId');if(!v.vehicleId||!unitId)return json(res,400,{error:'unit_context_required'});return json(res,200,{details:await freeUnitDetails(v,unitId)})}catch(e){return json(res,503,{error:e.message||'free_parts_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/free/search'){try{const v={catalog:'free',vehicleId:url.searchParams.get('vehicleId')},q=String(url.searchParams.get('q')||'').trim();if(!v.vehicleId||!q)return json(res,400,{error:'search_context_required'});return json(res,200,{query:q,results:await freeSearch(v,q)})}catch(e){return json(res,503,{error:e.message||'free_parts_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/free/analogs'){try{const article=String(url.searchParams.get('article')||'').trim();if(!article)return json(res,400,{error:'article_required'});return json(res,200,{analogs:await freeAnalogs(article)})}catch(e){return json(res,503,{error:e.message||'free_parts_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/meta'){return json(res,200,{...partsMeta(),examples:partSearchExamples})}
 if(req.method==='POST'&&url.pathname==='/api/parts/vin'){try{const b=await body(req);const vin=String(b.vin||'').trim().toUpperCase();if(!vin)return json(res,400,{error:'vin_required'});const vehicles=await findVehicle(vin);return json(res,200,{vehicles})}catch(e){return json(res,503,{error:e.message||'parts_provider_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/catalogs'){try{return json(res,200,{catalogs:await listCatalogs()})}catch(e){return json(res,503,{error:e.message||'parts_provider_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/wizard'){try{const catalog=url.searchParams.get('catalog');if(!catalog)return json(res,400,{error:'catalog_required'});return json(res,200,{steps:await wizard(catalog,url.searchParams.get('ssd')||'')})}catch(e){return json(res,503,{error:e.message||'parts_provider_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/wizard/find'){try{const catalog=url.searchParams.get('catalog'),ssd=url.searchParams.get('ssd');if(!catalog||!ssd)return json(res,400,{error:'wizard_context_required'});return json(res,200,{vehicles:await wizardFind(catalog,ssd)})}catch(e){return json(res,503,{error:e.message||'parts_provider_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/categories'){try{const v={catalog:url.searchParams.get('catalog'),vehicleId:url.searchParams.get('vehicleId'),ssd:url.searchParams.get('ssd')};if(!v.catalog||!v.vehicleId||!v.ssd)return json(res,400,{error:'vehicle_context_required'});return json(res,200,{categories:await listCategories(v)})}catch(e){return json(res,503,{error:e.message||'parts_provider_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/units'){try{const v={catalog:url.searchParams.get('catalog'),vehicleId:url.searchParams.get('vehicleId'),ssd:url.searchParams.get('ssd')};if(!v.catalog||!v.vehicleId||!v.ssd)return json(res,400,{error:'vehicle_context_required'});return json(res,200,{units:await listUnits(v,url.searchParams.get('categoryId')||'-1')})}catch(e){return json(res,503,{error:e.message||'parts_provider_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/unit-details'){try{const v={catalog:url.searchParams.get('catalog'),vehicleId:url.searchParams.get('vehicleId'),ssd:url.searchParams.get('ssd')};const unitId=url.searchParams.get('unitId');if(!v.catalog||!v.vehicleId||!v.ssd||!unitId)return json(res,400,{error:'unit_context_required'});return json(res,200,{details:await listDetailByUnit(v,unitId)})}catch(e){return json(res,503,{error:e.message||'parts_provider_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/search'){try{const v={catalog:url.searchParams.get('catalog'),vehicleId:url.searchParams.get('vehicleId'),ssd:url.searchParams.get('ssd')};const q=String(url.searchParams.get('q')||'').trim();if(!v.catalog||!v.vehicleId||!v.ssd||!q)return json(res,400,{error:'search_context_required'});return json(res,200,{query:q,results:await searchVehicleDetails(v,q)})}catch(e){return json(res,503,{error:e.message||'parts_provider_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/quick-groups'){try{const v={catalog:url.searchParams.get('catalog'),vehicleId:url.searchParams.get('vehicleId'),ssd:url.searchParams.get('ssd')};if(!v.catalog||!v.vehicleId||!v.ssd)return json(res,400,{error:'vehicle_context_required'});return json(res,200,{groups:await quickGroups(v)})}catch(e){return json(res,503,{error:e.message||'parts_provider_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/quick-details'){try{const v={catalog:url.searchParams.get('catalog'),vehicleId:url.searchParams.get('vehicleId'),ssd:url.searchParams.get('ssd')};const quickGroupId=url.searchParams.get('quickGroupId');if(!v.catalog||!v.vehicleId||!v.ssd||!quickGroupId)return json(res,400,{error:'quick_context_required'});return json(res,200,{results:await quickDetails(v,quickGroupId)})}catch(e){return json(res,503,{error:e.message||'parts_provider_unavailable'})}}
 if(req.method==='GET'&&url.pathname==='/api/parts/free/price-search'){const article=String(url.searchParams.get('article')||'').trim();const brand=String(url.searchParams.get('brand')||'').trim();const name=String(url.searchParams.get('name')||'').trim();if(!article)return json(res,400,{error:'article_required'});const q=encodeURIComponent([brand,article,name].filter(Boolean).join(' '));const configured=!!process.env.PARTS_PRICE_URL;return json(res,200,{article,brand,name,configured,averagePrice:null,priceMin:null,priceMax:null,source:configured?'provider':'web-search-link',searchUrl:`https://yandex.ru/search/?text=${q}`,message:configured?'Цена будет получена от подключённого ценового провайдера.':'Для этого варианта доступна ссылка на актуальный поиск цены; средняя цена не выдумывается без ценового источника.'})}
 if(req.method==='GET'&&url.pathname==='/api/vehicles/knowledge-meta'){return json(res,200,{version:'2.5-baseline',rules:VEHICLE_KNOWLEDGE.length,autoUpdateConfigured:!!KNOWLEDGE_UPDATE_URL,updatePeriodHours:24})}
 if(req.method==='GET'&&url.pathname==='/api/vehicles/models'){return json(res,200,{models:listVehicleModels(),count:listVehicleModels().length})}
 if(req.method==='GET'&&url.pathname==='/api/vehicles/recommendations'){const cars=Object.values(db.cars).filter(c=>c.userId===uid);const car=cars.find(c=>c.id===url.searchParams.get('carId'));if(!car)return json(res,404,{error:'car_not_found'});return json(res,200,{carId:car.id,recommendations:getVehicleRecommendations(car),knowledgeVersion:'2.5-baseline',autoUpdateConfigured:!!KNOWLEDGE_UPDATE_URL})}
 if(req.method==='GET'&&url.pathname==='/api/communities'){const models=listVehicleModels();const raw=String(url.searchParams.get('q')||'').trim();const q=raw.toUpperCase();const alias={
  'КАЛИНА':'KALINA','ГРАНТА':'GRANTA','ВЕСТА':'VESTA','НИВА':'NIVA','ПРИОРА':'PRIORA','ЛАРГУС':'LARGUS','Х-РЕЙ':'XRAY','Х РЕЙ':'XRAY','СОЛЯРИС':'SOLARIS','РИО':'RIO','ПОЛО':'POLO','ЛОГАН':'LOGAN','ДАСТЕР':'DUSTER','КРЕТА':'CRETA','РАВ4':'RAV4','КАМРИ':'CAMRY','КОРСА':'CORSA','АСТРА':'ASTRA','ФОКУС':'FOCUS','ОКТАВИЯ':'OCTAVIA','ТУКСОН':'TUCSON','СПОРТЕЙДЖ':'SPORTAGE'};
  const qq=alias[q]||q; let items=models.filter(x=>{const hay=`${x.make} ${x.model}`.toUpperCase();const aliases=[alias[String(x.model||'').toUpperCase()]||'',alias[String(x.make||'').toUpperCase()]||''].filter(Boolean);return !q||hay.includes(q)||hay.includes(qq)||aliases.some(a=>a.includes(qq)||qq.includes(a))}).map(x=>({make:x.make,model:x.model,name:`Владельцы ${x.make} ${x.model}`,connected:true}));if(!items.length&&alias[q]){const knownMake=['КАЛИНА','ГРАНТА','ВЕСТА','НИВА','ПРИОРА','ЛАРГУС','Х-РЕЙ','Х РЕЙ'].includes(q)?'LADA':'';if(knownMake)items=[{make:knownMake,model:alias[q],name:`Владельцы ${knownMake} ${alias[q]}`,connected:true,created:true}]}return json(res,200,{communities:items,query:raw})}
 if(req.method==='GET'&&url.pathname==='/api/communities/ensure'){const make=String(url.searchParams.get('make')||'').trim(),model=String(url.searchParams.get('model')||'').trim();if(!make||!model)return json(res,400,{error:'community_required'});return json(res,200,{community:{id:communityKey(make,model),make,model,name:`Владельцы ${make} ${model}`,created:true}})}
 if(req.method==='GET'&&url.pathname==='/api/communities/messages'){const make=url.searchParams.get('make')||'',model=url.searchParams.get('model')||'',key=communityKey(make,model);const messages=Object.values(db.communityMessages||{}).filter(m=>communityKey(m.make,m.model)===key).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).slice(-100);return json(res,200,{messages})}
 if(req.method==='POST'&&url.pathname==='/api/communities/messages'){const b=await body(req);const make=String(b.make||'').trim(),model=String(b.model||'').trim();if(!make||!model)return json(res,400,{error:'community_required',message:'Не удалось определить сообщество по марке и модели.'});if(!String(b.text||'').trim())return json(res,400,{error:'message_required'});const u=db.users[uid]||{};const msg=normalizeCommunityMessage({...b,make,model,userId:uid,authorName:u.username?`@${u.username}`:(u.firstName||'Владелец')});db.communityMessages[msg.id]=msg;saveSoon();return json(res,201,{community:{id:communityKey(make,model),make,model,name:`Владельцы ${make} ${model}`},message:msg})}
 if(req.method==='GET'&&url.pathname==='/api/mileage-analysis'){const carId=url.searchParams.get('carId')||'';const car=db.cars[carId];if(!car||car.userId!==uid)return json(res,404,{error:'car_not_found'});const rows=Object.values(db.mileageHistory||{}).filter(x=>x.userId===uid&&x.carId===carId).sort((a,b)=>new Date(a.recordedAt)-new Date(b.recordedAt));let kmPerDay=0,kmPerMonth=0;if(rows.length>=2){const first=rows[0],last=rows[rows.length-1];const days=Math.max(1,(new Date(last.recordedAt)-new Date(first.recordedAt))/86400000);const delta=Math.max(0,Number(last.odometer)-Number(first.odometer));kmPerDay=delta/days;kmPerMonth=kmPerDay*30.4375}const next=Number(car.odometer)+10000;const daysTo10k=kmPerDay>0?Math.ceil(10000/kmPerDay):null;const projected10kDate=daysTo10k?new Date(Date.now()+daysTo10k*86400000).toISOString().slice(0,10):null;return json(res,200,{carId,entries:rows.length,kmPerDay,kmPerMonth,next10k:{targetOdometer:next,days:daysTo10k,projectedDate:projected10kDate},message:rows.length<2?'Нужно минимум две записи пробега для расчёта среднего темпа.':'Расчёт основан на вашей истории пробега.'})} 
 if(req.method==='GET'&&url.pathname==='/api/dashboard'){const cars=Object.values(db.cars).filter(c=>c.userId===uid);const ms=Object.values(db.maintenance||{}).filter(m=>m.userId===uid);const services=Object.values(db.services||{}).filter(s=>s.userId===uid);const items=ms.map(m=>{const c=cars.find(x=>x.id===m.carId);if(!c)return null;const km=m.intervalKm!=null?m.intervalKm-(c.odometer-m.lastDoneOdometer):null;const days=m.nextDate?Math.ceil((new Date(`${m.nextDate}T23:59:59`)-new Date())/86400000):null;const due=(km!=null&&km<=0)||(days!=null&&days<=0);const soon=!due&&((km!=null&&km<=Number(m.reminderKm??1000))||(days!=null&&days<=Number(m.reminderDays??30)));const pct=m.intervalKm?Math.min(100,Math.max(0,100-(Math.max(0,km)/m.intervalKm*100))):null;return {...m,carId:c.id,carName:c.name,kmRemaining:km==null?null:Math.max(0,km),daysRemaining:days,progress:pct,due,soon};}).filter(Boolean).sort((a,b)=>(a.due?0:a.soon?1:2)-(b.due?0:b.soon?1:2));const totalSpent=services.reduce((n,s)=>n+Number(s.cost||0),0);const byMonth={};services.forEach(s=>{const k=String(s.date||'').slice(0,7);if(/^\d{4}-\d{2}$/.test(k))byMonth[k]=(byMonth[k]||0)+Number(s.cost||0)});const stats=Object.entries(byMonth).sort((a,b)=>b[0].localeCompare(a[0])).map(([month,cost])=>({month,cost}));return json(res,200,{attention:items.slice(0,12),summary:{cars:cars.length,maintenance:ms.length,due:items.filter(x=>x.due).length,soon:items.filter(x=>x.soon).length,totalSpent},monthlyExpenses:stats.slice(0,12)})} 
 if(req.method==='GET'&&url.pathname==='/api/calendar'){const from=url.searchParams.get('from')||new Date().toISOString().slice(0,10);const to=url.searchParams.get('to')||new Date(Date.now()+90*86400000).toISOString().slice(0,10);const cars=Object.values(db.cars).filter(c=>c.userId===uid);const ms=Object.values(db.maintenance||{}).filter(m=>m.userId===uid);const events=[];for(const m of ms){const c=cars.find(x=>x.id===m.carId);if(!c)continue;const km=m.intervalKm!=null?m.intervalKm-(c.odometer-m.lastDoneOdometer):null;if(m.nextDate&&m.nextDate>=from&&m.nextDate<=to)events.push({type:'maintenance',id:m.id,date:m.nextDate,name:m.name,carId:c.id,carName:c.name,kmRemaining:km});}for(const c of cars){if(c.nextServiceDate&&c.nextServiceDate>=from&&c.nextServiceDate<=to)events.push({type:'service',id:'general_'+c.id,date:c.nextServiceDate,name:'Общее ТО',carId:c.id,carName:c.name,kmRemaining:Math.max(0,c.serviceIntervalKm-(c.odometer-c.lastServiceOdometer))});}events.sort((a,b)=>a.date.localeCompare(b.date));return json(res,200,{from,to,events})}
 if(req.method==='GET'&&url.pathname==='/api/analytics'){const services=Object.values(db.services||{}).filter(s=>s.userId===uid);const byItem={};const byMonth={};const byCategory={};for(const s of services){const cost=Number(s.cost||0);const category=String(s.category||'maintenance');byCategory[category]=(byCategory[category]||0)+cost;for(const item of (s.items||[])){const k=String(item).trim()||'Другое';byItem[k]=(byItem[k]||0)+cost/Math.max(1,(s.items||[]).length)}const month=String(s.date||'').slice(0,7);if(/^\d{4}-\d{2}$/.test(month))byMonth[month]=(byMonth[month]||0)+cost}return json(res,200,{total:services.reduce((n,s)=>n+Number(s.cost||0),0),byCategory:Object.entries(byCategory).sort((a,b)=>b[1]-a[1]).map(([name,cost])=>({name,cost})),byItem:Object.entries(byItem).sort((a,b)=>b[1]-a[1]).map(([name,cost])=>({name,cost})),byMonth:Object.entries(byMonth).sort((a,b)=>b[0].localeCompare(a[0])).map(([month,cost])=>({month,cost}))})} 
 if(req.method==='POST'&&url.pathname==='/api/import'){const b=await body(req);if(!b||!Array.isArray(b.cars)||!Array.isArray(b.maintenance)||!Array.isArray(b.services))return json(res,400,{error:'invalid_backup'});for(const key of ['cars','maintenance','services','fines','drivers','stationViews','stations','stationReviews','bookings','communityMessages','mileageHistory'])for(const [k,v] of Object.entries(db[key]||{}))if(v.userId===uid)delete db[key][k];for(const car0 of b.cars){const car=normalizeCar({...car0,userId:uid,id:id('car')});db.cars[car.id]=car}const idMap=new Map();const oldCars=b.cars;const newCars=Object.values(db.cars).filter(c=>c.userId===uid);oldCars.forEach((c,i)=>idMap.set(c.id,newCars[i]?.id));for(const m0 of b.maintenance){const carId=idMap.get(m0.carId);if(!carId)continue;db.maintenance[id('maint')]=normalizeMaintenance({...m0,id:id('maint'),userId:uid,carId})}for(const s0 of b.services){const carId=idMap.get(s0.carId);if(!carId)continue;db.services[id('svc')]=normalizeService({...s0,id:id('svc'),userId:uid,carId})}for(const f0 of (b.fines||[])){db.fines[id('fine')]=normalizeFine({...f0,id:id('fine'),userId:uid,carId:idMap.get(f0.carId)||''})}for(const d0 of (b.drivers||[])){db.drivers[id('driver')]=normalizeDriver({...d0,id:id('driver'),userId:uid})}for(const v0 of (b.stationViews||[])){db.stationViews[id('view')]=normalizeStationView({...v0,id:id('view'),userId:uid})}for(const x0 of (b.stations||[])){db.stations[id('station')]=normalizeStation({...x0,id:id('station'),userId:uid})}for(const x0 of (b.stationReviews||[])){db.stationReviews[id('review')]=normalizeReview({...x0,id:id('review'),userId:uid})}for(const x0 of (b.bookings||[])){db.bookings[id('booking')]=normalizeBooking({...x0,id:id('booking'),userId:uid})}for(const x0 of (b.communityMessages||[])){db.communityMessages[id('msg')]=normalizeCommunityMessage({...x0,id:id('msg'),userId:uid})}for(const h0 of (b.mileageHistory||[])){const carId=idMap.get(h0.carId);if(carId)db.mileageHistory[id('mile')]=normalizeMileageHistory({...h0,id:id('mile'),userId:uid,carId})}saveSoon();return json(res,200,{ok:true,cars:newCars.length,message:'Резервная копия восстановлена'})}
 if(req.method==='GET'&&url.pathname==='/api/export'){return json(res,200,{exportedAt:new Date().toISOString(),version:'2.7.0',user:db.users[uid],cars:Object.values(db.cars).filter(x=>x.userId===uid),maintenance:Object.values(db.maintenance||{}).filter(x=>x.userId===uid),services:Object.values(db.services||{}).filter(x=>x.userId===uid),fines:Object.values(db.fines||{}).filter(x=>x.userId===uid),drivers:Object.values(db.drivers||{}).filter(x=>x.userId===uid),stationViews:Object.values(db.stationViews||{}).filter(x=>x.userId===uid),stations:Object.values(db.stations||{}).filter(x=>x.userId===uid),stationReviews:Object.values(db.stationReviews||{}).filter(x=>x.userId===uid),bookings:Object.values(db.bookings||{}).filter(x=>x.userId===uid),communityMessages:Object.values(db.communityMessages||{}).filter(x=>x.userId===uid),mileageHistory:Object.values(db.mileageHistory||{}).filter(x=>x.userId===uid)})}
 if(req.method==='GET'&&url.pathname==='/api/state'){const fines=Object.values(db.fines).filter(f=>f.userId===uid);const drivers=Object.values(db.drivers||{}).filter(d=>d.userId===uid);const favorites=Object.values(db.stations).filter(s=>s.userId===uid);const cars=Object.values(db.cars).filter(c=>c.userId===uid).map(safeCar);const services=Object.values(db.services).filter(s=>s.userId===uid).sort((a,b)=>b.date.localeCompare(a.date));const maintenance=Object.values(db.maintenance||{}).filter(m=>m.userId===uid).sort((a,b)=>String(a.nextDate||'9999').localeCompare(String(b.nextDate||'9999')));return json(res,200,{user:db.users[uid],cars,services,maintenance,fines,drivers,favoriteStations:favorites,mileageHistory:Object.values(db.mileageHistory||{}).filter(x=>x.userId===uid).sort((a,b)=>b.recordedAt.localeCompare(a.recordedAt))})}
 if(req.method==='POST'&&url.pathname==='/api/car'){const b=await body(req);const car=normalizeCar(b);car.userId=uid;db.cars[car.id]=car;recordMileage(uid,car,car.odometer,'initial');saveSoon();return json(res,201,{car:safeCar(car)})}
 if(req.method==='PUT'&&url.pathname.startsWith('/api/car/')){const carId=url.pathname.split('/').pop();const b=await body(req);const car=db.cars[carId];if(!car||car.userId!==uid)return json(res,404,{error:'car_not_found'});const incoming=normalizeCar({...car,...b,id:carId});if(incoming.odometer<car.odometer)return json(res,400,{error:'odometer_must_not_decrease'});incoming.userId=uid;db.cars[carId]=incoming;if(incoming.odometer!==car.odometer)recordMileage(uid,incoming,incoming.odometer,'manual');saveSoon();return json(res,200,{car:safeCar(incoming)})}
if(req.method==='DELETE'&&url.pathname.startsWith('/api/car/')){const carId=url.pathname.split('/').pop();const car=db.cars[carId];if(!car||car.userId!==uid)return json(res,404,{error:'car_not_found'});for(const [k,v] of Object.entries(db.maintenance||{}))if(v.carId===carId&&v.userId===uid)delete db.maintenance[k];for(const [k,v] of Object.entries(db.services||{}))if(v.carId===carId&&v.userId===uid)delete db.services[k];for(const [k,v] of Object.entries(db.mileageHistory||{}))if(v.carId===carId&&v.userId===uid)delete db.mileageHistory[k];delete db.cars[carId];saveSoon();return json(res,200,{ok:true})}
 if(req.method==='GET'&&url.pathname==='/api/car/mileage-history'){const carId=url.searchParams.get('carId')||'';const car=db.cars[carId];if(!car||car.userId!==uid)return json(res,404,{error:'car_not_found'});const history=Object.values(db.mileageHistory||{}).filter(x=>x.userId===uid&&x.carId===carId).sort((a,b)=>b.recordedAt.localeCompare(a.recordedAt));return json(res,200,{history})}
 if(req.method==='POST'&&url.pathname==='/api/car/odometer'){const b=await body(req);const car=db.cars[b.carId];if(!car||car.userId!==uid)return json(res,404,{error:'car_not_found'});const value=Number(b.odometer);if(!Number.isFinite(value)||value<car.odometer)return json(res,400,{error:'odometer_must_not_decrease'});const warning=suspiciousMileage(car,value);if(warning&&!b.acknowledgeSuspicious)return json(res,409,{error:'suspicious_odometer',warning,requiresConfirmation:true,message:`Пробег отличается на ${warning.delta.toLocaleString('ru-RU')} км. Если значение верное, подтвердите сохранение.`});car.odometer=value;car.updatedAt=new Date().toISOString();car.mileageReminder={...(car.mileageReminder||{}),lastAskedAt:new Date().toISOString()};recordMileage(uid,car,value,'manual');saveSoon();return json(res,200,{car:safeCar(car)})}
 if(req.method==='POST'&&url.pathname==='/api/maintenance'){const b=await body(req);const car=db.cars[b.carId];if(!car||car.userId!==uid)return json(res,404,{error:'car_not_found'});const intervalKm=Number(b.intervalKm);const nextDate=/^\d{4}-\d{2}-\d{2}$/.test(b.nextDate||'')?b.nextDate:null;const m={id:id('maint'),userId:uid,carId:car.id,name:String(b.name||'ТО/расходник').slice(0,120),presetKey:String(b.presetKey||'').slice(0,80),group:String(b.group||'').slice(0,50),general:b.general===true,lastDoneDate:/^\d{4}-\d{2}-\d{2}$/.test(b.lastDoneDate||'')?b.lastDoneDate:new Date().toISOString().slice(0,10),lastDoneOdometer:Number.isFinite(Number(b.lastDoneOdometer))?Number(b.lastDoneOdometer):car.odometer,intervalKm:Number.isFinite(intervalKm)&&intervalKm>0?intervalKm:null,nextDate,notes:String(b.notes||'').slice(0,500),category:['maintenance','repair'].includes(String(b.category))?String(b.category):'maintenance',reminderKm:Number.isFinite(Number(b.reminderKm))&&Number(b.reminderKm)>=0?Number(b.reminderKm):1000,reminderDays:Number.isFinite(Number(b.reminderDays))&&Number(b.reminderDays)>=0?Number(b.reminderDays):30,lastCost:Math.max(0,Number(b.lastCost)||0),details:b.details&&typeof b.details==='object'?b.details:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};db.maintenance[m.id]=m;saveSoon();return json(res,201,{maintenance:m})}
 if(req.method==='PUT'&&url.pathname.startsWith('/api/maintenance/')){const mid=url.pathname.split('/').pop();const m=db.maintenance[mid];if(!m||m.userId!==uid)return json(res,404,{error:'maintenance_not_found'});const b=await body(req);if(b.carId&&(!db.cars[b.carId]||db.cars[b.carId].userId!==uid))return json(res,404,{error:'car_not_found'});if(b.name!==undefined)m.name=String(b.name).slice(0,120);if(b.intervalKm!==undefined)m.intervalKm=b.intervalKm===null?null:(Number.isFinite(Number(b.intervalKm))&&Number(b.intervalKm)>0?Number(b.intervalKm):m.intervalKm);if(b.nextDate!==undefined)m.nextDate=b.nextDate===null?null:(/^\d{4}-\d{2}-\d{2}$/.test(b.nextDate)?b.nextDate:m.nextDate);if(b.notes!==undefined)m.notes=String(b.notes).slice(0,500);if(b.details!==undefined)m.details=b.details&&typeof b.details==='object'?b.details:null;if(b.presetKey!==undefined)m.presetKey=String(b.presetKey).slice(0,80);if(b.group!==undefined)m.group=String(b.group).slice(0,50);if(b.general!==undefined)m.general=b.general===true;if(b.reminderKm!==undefined)m.reminderKm=Math.max(0,Number(b.reminderKm)||0);if(b.reminderDays!==undefined)m.reminderDays=Math.max(0,Number(b.reminderDays)||0);m.updatedAt=new Date().toISOString();saveSoon();return json(res,200,{maintenance:m})}
 if(req.method==='DELETE'&&url.pathname.startsWith('/api/maintenance/')){const mid=url.pathname.split('/').pop();const m=db.maintenance[mid];if(!m||m.userId!==uid)return json(res,404,{error:'maintenance_not_found'});delete db.maintenance[mid];saveSoon();return json(res,200,{ok:true})}
 if(req.method==='POST'&&url.pathname==='/api/maintenance/complete'){const b=await body(req);const m=db.maintenance[b.maintenanceId];if(!m||m.userId!==uid)return json(res,404,{error:'maintenance_not_found'});const car=db.cars[m.carId];const useAppMileage=b.useAppMileage===true;const scheduledKm=Number(m.lastDoneOdometer||car?.odometer)+(Number(m.intervalKm)||0);const km=useAppMileage?scheduledKm:Number(b.odometer??car?.odometer);if(!car||!Number.isFinite(km)||km<0)return json(res,400,{error:'odometer_invalid'});if(!useAppMileage&&km<car.odometer)return json(res,400,{error:'odometer_invalid'});m.lastDoneOdometer=km;m.lastDoneDate=/^\d{4}-\d{2}-\d{2}$/.test(b.date||'')?b.date:new Date().toISOString().slice(0,10);if(b.nextDate!==undefined)m.nextDate=b.nextDate||null;if(b.cost!==undefined)m.lastCost=Math.max(0,Number(b.cost)||0);if(b.notes!==undefined)m.notes=String(b.notes).slice(0,500);if(b.details!==undefined)m.details=b.details&&typeof b.details==='object'?b.details:null;m.updatedAt=new Date().toISOString();car.odometer=useAppMileage?Math.max(car.odometer,km):km;car.lastServiceDate=m.lastDoneDate;car.lastServiceOdometer=km;car.updatedAt=new Date().toISOString();recordMileage(uid,car,car.odometer,'maintenance');if(b.oil){car.oil=normalizeOil(b.oil);car.oilVolume=car.oil.volume}const svc={id:id('svc'),userId:uid,carId:car.id,date:m.lastDoneDate,odometer:km,items:Array.isArray(b.items)&&b.items.length?b.items.map(String).slice(0,30):[m.name],category:String(m.category||'maintenance'),cost:m.lastCost,note:m.notes||'',oil:car.oil};db.services[svc.id]=svc;saveSoon();return json(res,200,{maintenance:m,service:svc,car:safeCar(car)})}
 if(req.method==='POST'&&url.pathname==='/api/service'){const b=await body(req);const car=db.cars[b.carId];if(!car||car.userId!==uid)return json(res,404,{error:'car_not_found'});const km=Number(b.odometer);if(!Number.isFinite(km)||km<car.odometer)return json(res,400,{error:'service_odometer_invalid'});const svc={id:id('svc'),userId:uid,carId:car.id,date:/^\d{4}-\d{2}-\d{2}$/.test(b.date||'')?b.date:new Date().toISOString().slice(0,10),odometer:km,items:Array.isArray(b.items)?b.items.map(String).slice(0,30):[],category:['maintenance','repair','fuel','tires','wash','other'].includes(String(b.category))?String(b.category):'maintenance',cost:Math.max(0,Number(b.cost)||0),note:String(b.note||'').slice(0,1000)};db.services[svc.id]=svc;car.lastServiceOdometer=svc.odometer;car.odometer=svc.odometer;recordMileage(uid,car,car.odometer,'service');if(b.nextServiceDate!==undefined)car.nextServiceDate=b.nextServiceDate||null;saveSoon();return json(res,201,{service:svc,car:safeCar(car)})}
 if(req.method==='PUT'&&url.pathname.startsWith('/api/service/')){const sid=url.pathname.split('/').pop();const svc=db.services[sid];if(!svc||svc.userId!==uid)return json(res,404,{error:'service_not_found'});const b=await body(req);if(b.date!==undefined&&/^\d{4}-\d{2}-\d{2}$/.test(b.date))svc.date=b.date;if(b.items!==undefined&&Array.isArray(b.items))svc.items=b.items.map(String).slice(0,30);if(b.category!==undefined&&['maintenance','repair','fuel','tires','wash','other'].includes(String(b.category)))svc.category=String(b.category);if(b.cost!==undefined)svc.cost=Math.max(0,Number(b.cost)||0);if(b.note!==undefined)svc.note=String(b.note).slice(0,1000);svc.updatedAt=new Date().toISOString();saveSoon();return json(res,200,{service:svc})}
 if(req.method==='DELETE'&&url.pathname.startsWith('/api/service/')){const sid=url.pathname.split('/').pop();const svc=db.services[sid];if(!svc||svc.userId!==uid)return json(res,404,{error:'service_not_found'});delete db.services[sid];saveSoon();return json(res,200,{ok:true})}

 if(req.method==='GET'&&url.pathname==='/api/fines'){const fines=Object.values(db.fines).filter(f=>f.userId===uid).sort((a,b)=>b.date.localeCompare(a.date));return json(res,200,{fines,configured:!!FINES_API_URL})}
 if(req.method==='GET'&&url.pathname==='/api/drivers'){return json(res,200,{drivers:Object.values(db.drivers||{}).filter(d=>d.userId===uid)})}
 if(req.method==='POST'&&url.pathname==='/api/driver'){const b=await body(req);const d=normalizeDriver({...b,userId:uid});if(!d.licenseNumber)return json(res,400,{error:'license_number_required'});db.drivers[d.id]=d;saveSoon();return json(res,201,{driver:d})}
 if(req.method==='DELETE'&&url.pathname.startsWith('/api/driver/')){const did=url.pathname.split('/').pop();const d=db.drivers[did];if(!d||d.userId!==uid)return json(res,404,{error:'driver_not_found'});delete db.drivers[did];saveSoon();return json(res,200,{ok:true})}
 if(req.method==='POST'&&url.pathname==='/api/fines/check'){if(!FINES_API_URL)return json(res,503,{ok:false,available:false,provider:'not_configured',message:'Для реальной автоматической проверки нужен подключённый официальный/лицензированный провайдер данных о штрафах. Ручной ввод штрафов отключён.'});const cars=Object.values(db.cars).filter(c=>c.userId===uid);const drivers=Object.values(db.drivers||{}).filter(d=>d.userId===uid);let added=0;for(const car of cars){const r=await fetchFineProvider({vehicle:{plate:car.plate,sts:car.stsNumber,vin:car.vin},drivers:drivers.map(d=>({licenseNumber:d.licenseNumber,licenseIssueDate:d.licenseIssueDate}))});for(const x of r.fines){const f=normalizeFine({...x,userId:uid,carId:car.id,source:'provider'});const exists=Object.values(db.fines).find(z=>z.userId===uid&&z.externalId&&z.externalId===f.externalId);if(!exists){db.fines[f.id]=f;added++}}}saveSoon();return json(res,200,{ok:true,available:true,provider:'configured',added,fines:Object.values(db.fines).filter(f=>f.userId===uid)})}
 if(req.method==='GET'&&url.pathname==='/api/stations/search'){try{const text=url.searchParams.get('q')||'автосервис';const lat=Number(url.searchParams.get('lat')),lon=Number(url.searchParams.get('lon'));const r=await searchStations(text,lat,lon);return json(res,200,r)}catch(e){return json(res,502,{error:'station_search_failed'})}}
 if(req.method==='POST'&&url.pathname==='/api/station/favorite'){const b=await body(req);const st={id:String(b.id||id('station')),userId:uid,externalId:String(b.externalId||b.id||'').slice(0,120),name:String(b.name||'СТО').slice(0,160),address:String(b.address||'').slice(0,300),phone:String(b.phone||'').slice(0,50),lat:Number(b.lat),lon:Number(b.lon),notes:String(b.notes||'').slice(0,500),sponsored:b.sponsored===true,createdAt:new Date().toISOString()};db.stations[st.id]=st;saveSoon();return json(res,201,{station:st})}
 if(req.method==='GET'&&url.pathname==='/api/stations/favorites'){return json(res,200,{stations:Object.values(db.stations).filter(s=>s.userId===uid)})}
 if(req.method==='GET'&&url.pathname==='/api/stations/recent'){return json(res,200,{stations:Object.values(db.stationViews||{}).filter(s=>s.userId===uid).sort((a,b)=>b.viewedAt.localeCompare(a.viewedAt)).slice(0,10)})}
 if(req.method==='POST'&&url.pathname==='/api/station/view'){const b=await body(req);const k=`${uid}_${String(b.externalId||b.id||'')}`;db.stationViews[k]={id:k,userId:uid,externalId:String(b.externalId||b.id||''),name:String(b.name||'СТО').slice(0,160),address:String(b.address||'').slice(0,300),phone:String(b.phone||'').slice(0,50),lat:Number(b.lat),lon:Number(b.lon),viewedAt:new Date().toISOString()};saveSoon();return json(res,201,{ok:true})}
 if(req.method==='GET'&&url.pathname==='/api/station/reviews'){const stationId=url.searchParams.get('stationId')||'';const reviews=Object.values(db.stationReviews||{}).filter(r=>r.stationId===stationId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));return json(res,200,{reviews,summary:stationSummary(stationId)})}
 if(req.method==='POST'&&url.pathname==='/api/station/review'){const b=await body(req);if(!b.stationId)return json(res,400,{error:'station_id_required'});const r=normalizeReview({...b,userId:uid});db.stationReviews[r.id]=r;saveSoon();return json(res,201,{review:r,summary:stationSummary(r.stationId)})}
 if(req.method==='POST'&&url.pathname==='/api/station/booking'){const b=await body(req);if(!b.stationId||!b.carId)return json(res,400,{error:'station_and_car_required'});const car=db.cars[b.carId];if(!car||car.userId!==uid)return json(res,404,{error:'car_not_found'});const bk=normalizeBooking({...b,userId:uid});db.bookings[bk.id]=bk;saveSoon();return json(res,201,{booking:bk})}
 if(req.method==='GET'&&url.pathname==='/api/station/bookings'){return json(res,200,{bookings:Object.values(db.bookings||{}).filter(b=>b.userId===uid).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))})}
 if(req.method==='POST'&&url.pathname==='/api/promo/redeem'){const b=await body(req);const promo=Object.values(db.promos||{}).find(p=>p.code===String(b.code||'').trim().toUpperCase()&&p.active);if(!promo)return json(res,404,{error:'promo_not_found'});if(promo.validUntil&&promo.validUntil<new Date().toISOString().slice(0,10))return json(res,400,{error:'promo_expired'});return json(res,200,{ok:true,promo})}
 if(req.method==='GET'&&url.pathname==='/api/promos'){const stationId=url.searchParams.get('stationId')||'';return json(res,200,{promos:Object.values(db.promos||{}).filter(p=>p.stationId===stationId&&p.active)})}
 if(req.method==='POST'&&url.pathname==='/api/settings'){const b=await body(req);const mode=['weekly','biweekly','monthly'].includes(b.mode)?b.mode:'weekly';const weekday=Math.min(6,Math.max(0,Number(b.weekday)||0));const monthlyDay=Math.min(31,Math.max(1,Number(b.monthlyDay)||1));const time=/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(b.time||'')?b.time:'19:00';db.users[uid].reminder={enabled:b.enabled===true,mode,weekday,time,monthlyDay};saveSoon();return json(res,200,{user:db.users[uid]})}
 if(req.method==='POST'&&url.pathname==='/api/car/mileage-reminder'){const b=await body(req);const car=db.cars[b.carId];if(!car||car.userId!==uid)return json(res,404,{error:'car_not_found'});const mode=['interval','monthly'].includes(b.mode)?b.mode:'interval';car.mileageReminder={enabled:b.enabled!==false,mode,intervalDays:Math.min(30,Math.max(1,Number(b.intervalDays)||7)),monthlyDay:Math.min(31,Math.max(1,Number(b.monthlyDay)||1)),lastAskedAt:car.mileageReminder?.lastAskedAt||null};saveSoon();return json(res,200,{car:safeCar(car)})}
 if(req.method==='POST'&&url.pathname==='/api/reminder/request-mileage'){const b=await body(req);const car=db.cars[b.carId];if(!car||car.userId!==uid)return json(res,404,{error:'car_not_found'});if(!BOT_TOKEN)return json(res,503,{error:'telegram_bot_not_configured'});db.pendingMileage[uid]={carId:car.id,createdAt:Date.now()};saveSoon();await telegram('sendMessage',{chat_id:uid,text:`📏 Какой сейчас пробег у ${car.name}?\n\nОтправьте число в километрах.`});return json(res,200,{ok:true})}
 if(req.method==='GET'){const file=url.pathname==='/'||url.pathname==='/index.html'?'index.html':decodeURIComponent(url.pathname).replace(/^\/+/, '');const path=resolve(PUBLIC,file);const rel=relative(PUBLIC,path);if(isAbsolute(rel)||rel==='..'||rel.startsWith('..\\'))return json(res,403,{error:'forbidden'});try{const data=await readFile(path);const ext=extname(path);const ct={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json'}[ext]||'application/octet-stream';res.writeHead(200,{'content-type':ct});res.end(data)}catch{json(res,404,{error:'not_found'})};return}
 json(res,404,{error:'not_found'})
}

async function checkUserFinesAndNotify(uid){
 if(!FINES_API_URL||!BOT_TOKEN)return {checked:false,added:0};
 const cars=Object.values(db.cars).filter(c=>c.userId===uid); const drivers=Object.values(db.drivers||{}).filter(d=>d.userId===uid); let added=[];
 for(const car of cars){
  try{const r=await fetchFineProvider({vehicle:{plate:car.plate,sts:car.stsNumber,vin:car.vin},drivers:drivers.map(d=>({licenseNumber:d.licenseNumber,licenseIssueDate:d.licenseIssueDate}))});
   for(const x of r.fines){const f=normalizeFine({...x,userId:uid,carId:car.id,source:'provider'});const exists=Object.values(db.fines).find(z=>z.userId===uid&&z.externalId&&z.externalId===f.externalId);if(!exists){db.fines[f.id]=f;added.push(f)}}
  }catch(e){console.error('fine provider check failed',e.message)}
 }
 if(added.length){saveSoon(); await telegram('sendMessage',{chat_id:uid,text:`⚠️ АвтоПлан: найдено новых штрафов: ${added.length}. Откройте раздел «Штрафы» в приложении.`}).catch(()=>{})}
 return {checked:true,added:added.length};
}
function shouldAskMileage(car){if(!car.mileageReminder?.enabled)return false;const now=new Date();if(car.mileageReminder.mode==='monthly')return now.getDate()===Math.min(car.mileageReminder.monthlyDay,new Date(now.getFullYear(),now.getMonth()+1,0).getDate()) && (!car.mileageReminder.lastAskedAt||String(car.mileageReminder.lastAskedAt).slice(0,10)!==now.toISOString().slice(0,10));const last=car.mileageReminder.lastAskedAt?new Date(car.mileageReminder.lastAskedAt):null;return !last||((now-last)/86400000>=Number(car.mileageReminder.intervalDays||7));}
async function runMileageScheduler(){if(!BOT_TOKEN)return;for(const uid of Object.keys(db.users)){const cars=Object.values(db.cars).filter(c=>c.userId===uid);for(const car of cars){if(!shouldAskMileage(car))continue;try{await telegram('sendMessage',{chat_id:uid,text:`📏 Пора обновить пробег
${car.name}

Текущий пробег в АвтоПлане: ${Number(car.odometer).toLocaleString('ru-RU')} км
Введите актуальный пробег в Mini App или ответьте числом в этом чате.`});car.mileageReminder.lastAskedAt=new Date().toISOString();db.pendingMileage[uid]={carId:car.id,createdAt:Date.now()};saveSoon()}catch{}}}}
function startFineScheduler(){if(!FINES_API_URL||!BOT_TOKEN)return;setInterval(async()=>{for(const uid of Object.keys(db.users)){await checkUserFinesAndNotify(uid)}},30*60*1000)}
http.createServer((req,res)=>route(req,res).catch(e=>{console.error(e);json(res,500,{error:'server_error'})})).listen(PORT,()=>{console.log(`Auto Planner 2.7.0 listening on ${PORT}`);startFineScheduler()});refreshKnowledge().catch(()=>{});setInterval(()=>refreshKnowledge(),24*60*60*1000);

